### ISSUE TITLE
Type definitions error after upgrade: missing inherited URL properties

### ISSUE THREAD

**Issue by nbbeeken** [mongodb-js/mongodb-connection-string-url#2]
Using typescript version 4.3.5 the recent change in #1 has somehow removed the types for the inherited properties from `URL`. Is it expected to need the `@types/whatwg-url` package as a separate dependency now? (I think we can swing it if so 😄  just wanna make sure this wasn't unexpected) 

### Errors

```
main.ts(5,3): error TS2339: Property 'username' does not exist on type 'ConnectionString'.
main.ts(6,3): error TS2339: Property 'password' does not exist on type 'ConnectionString'.
main.ts(7,3): error TS2339: Property 'searchParams' does not exist on type 'ConnectionString'.
main.ts(8,3): error TS2339: Property 'pathname' does not exist on type 'ConnectionString'.
```

### Steps to repeat

- `npm i mongodb-connection-string-url typescript`
- `npx tsc --init && touch main.ts`
- Paste snippet into `main.ts` and run `npx tsc`

```typescript
import ConnectionString from 'mongodb-connection-string-url'

const c = new ConnectionString('mongodb://localhost')

c.username
c.password
c.searchParams
c.pathname
```

**Comment by addaleax** [comment]
@nbbeeken Thanks for bringing this up! This is fixed in `mongodb-connection-string-url@1.0.2` by including the types for whatwg-url as a full dependency :+1:
