### ISSUE TITLE
DeprecationWarning: The 'punycode' module is deprecated. Please use a userland alternative instead.

### ISSUE THREAD

**Issue by AaronActu** [mongodb-js/mongodb-connection-string-url#30]
## Problem
With the release of Node.js version 21, the internal `punycode` API has been deprecated. More details on this can be found here: [Node.js Punycode API Documentation](https://nodejs.org/api/punycode.html).

From our stack trace analysis, the `tr46` package seems to be the root cause of this issue. This project currently relies on the `whatwg-url` package, which in turn depends on `tr46`.

The latest versions of `whatwg-url` (currently at v13.0.0) and `tr46` (currently at v4.1.1) have addressed this deprecation notice. However, our project is currently using an older version of `whatwg-url` (v11.0.0), which does not include these updates.

#### Stacktrace 
> DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
    at node:punycode:3:9
    at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/realm:392:7)
    at BuiltinModule.compileForPublicLoader (node:internal/bootstrap/realm:328:10)
    at loadBuiltinModule (node:internal/modules/helpers:101:7)
    at Function.Module._load (node:internal/modules/cjs/loader:1001:17)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/usr/src/app/node_modules/mongodb-connection-string-url/node_modules/tr46/index.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)

## Solution
To resolve this, I have created a Pull Request to update the whatwg-url package to its latest version. This update is crucial to ensure compatibility with Node.js v21 and to avoid potential issues related to the deprecated punycode API.

Please review the changes proposed in the Pull Request and consider merging it to maintain the project's compatibility with the latest Node.js standards.

Thank you!

**Comment by addaleax** [comment]
Just linking https://jira.mongodb.org/browse/NODE-5709 as the ticket where we track this in our company JIRA instance.

**Comment by AaronActu** [comment]
Great @addaleax ! Is there anything I can do to speed things up?

**Comment by addaleax** [comment]
@AaronActu Done, and released in 3.0.0! (Unfortunately, whatwg-url bumped its minimum Node.js version to 16, so we're just matching that after this bump)

**Comment by hdlslm** [comment]
> @AaronActu Done, and released in 3.0.0! (Unfortunately, whatwg-url bumped its minimum Node.js version to 16, so we're just matching that after this bump)

sorry but i'm a little confused , is there a fix for this as of yet? i checked whatwg-url and the minimum node.js version is now 18 if that helps anything. thanks in advanced!!

**Comment by leta-krahenbuhl** [comment]
Hi! I'm using node v21.7.3 with whatwg-url v13.0.0 and tr46 v4.1.1 but I still get the DeprecationWarning – is this the right place to ask why?

**Comment by addaleax** [comment]
@leta-krahenbuhl That's hard to tell, but you'll probably want to run your code with `node --trace-deprecation ...` and then share the full stack trace for the deprecation warning in question

**Comment by AaronActu** [comment]
(@addaleax I was about to comment but I forgot how fast you were ⚡️)

@leta-krahenbuhl It could be related to the package that has `mongodb-connection-string-url` in its dependencies. If it doesn't depend, at least on the v3.0.0 of that package, that might explain why you're still getting this error.

(cc: @hdlslm )
