### ISSUE TITLE
update whatwg-url dependency to fix buffer error in electron 14+

### ISSUE THREAD

**Issue by Patronics** [mongodb-js/mongodb-connection-string-url#8]
See https://github.com/jsdom/whatwg-url/issues/211 for a description of the issue. It seems to have been fixed in whatwg-url 11.0.0, which comes with webidl-coonversions 7.0.0, which fixes the issue.

**Comment by has-n** [comment]
+1 for this. This is used downstream in the official mongodb Node driver which now breaks for Node 14+.
